version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: store-db-prod
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./store-backend/.env
    networks:
      - store-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U store -d store"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: registry.digitalocean.com/mystore/copilot-store-backend:latest
    container_name: store-backend-prod
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./store-backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - store-network

  frontend:
    image: registry.digitalocean.com/mystore/copilot-store-frontend:latest
    container_name: store-frontend-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - store-network

volumes:
  postgres_data:

networks:
  store-network:
    driver: bridge
