version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./store-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./store-backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./store-backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./store-frontend
    command: npm run dev -- --host
    volumes:
      - ./store-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./store-frontend/.env

volumes:
  postgres_data:
