"""Initial migration

Revision ID: b240a2d38d70
Revises: 
Create Date: 2025-08-01 06:14:57.885877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b240a2d38d70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('amount_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_email'), 'order', ['customer_email'], unique=False)
    op.create_index(op.f('ix_order_stripe_checkout_session_id'), 'order', ['stripe_checkout_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_stripe_checkout_session_id'), table_name='order')
    op.drop_index(op.f('ix_order_customer_email'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
