name: Build, Push, and Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: registry.digitalocean.com/mystore
  IMAGE_NAME_BACKEND: copilot-store-backend
  IMAGE_NAME_FRONTEND: copilot-store-frontend

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./store-backend/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./store-frontend/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:latest

  deploy:
    name: Deploy to Droplet
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME_BACKEND: ${{ env.IMAGE_NAME_BACKEND }}
          IMAGE_NAME_FRONTEND: ${{ env.IMAGE_NAME_FRONTEND }}
          DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          password: ${{ secrets.DO_DROPLET_PASSWORD }}
          envs: REGISTRY,IMAGE_NAME_BACKEND,IMAGE_NAME_FRONTEND,DO_TOKEN
          script: |
            echo "Setting up project directory..."
            mkdir -p ~/store
            cd ~/store
            
            echo "Checking if git repository exists..."
            if [ ! -d .git ]; then
              echo "Cloning repository..."
              git clone https://github.com/GuZixuan202507142/store.git .
            else
              echo "Updating repository..."
              git fetch origin
              git reset --hard origin/main
            fi
            
            echo "Copying production environment file..."
            if [ -f ./store-backend/.env.production ]; then
              cp ./store-backend/.env.production ./store-backend/.env
            else
              echo "Warning: .env.production file not found, creating basic .env file"
              touch ./store-backend/.env
            fi

            echo "Logging into DigitalOcean Container Registry..."
            echo "$DO_TOKEN" | docker login registry.digitalocean.com -u $DO_TOKEN --password-stdin
            
            echo "Pulling latest images..."
            docker pull $REGISTRY/$IMAGE_NAME_BACKEND:latest
            docker pull $REGISTRY/$IMAGE_NAME_FRONTEND:latest
            
            echo "Stopping and removing old containers..."
            docker-compose -f docker-compose.prod.yml down || true
            
            echo "Starting new containers..."
            docker-compose -f docker-compose.prod.yml up -d
            
            echo "Deployment complete."
